# Generated by Django 4.2.9 on 2024-06-03 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leavetype", models.CharField(max_length=255)),
                ("Description", models.TextField()),
                ("PostingDate", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leave_type", models.CharField(default="Annual", max_length=100)),
                ("posting_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[(0, "Pending"), (1, "Approved"), (2, "Declined")],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("leavetype", models.CharField(default=None, max_length=255)),
                ("description", models.TextField(default=None)),
                ("fromdate", models.DateField(default=None)),
                ("todate", models.DateField(default=None)),
                ("isread", models.IntegerField(default=0)),
                (
                    "admin_remark",
                    models.CharField(default=None, max_length=255, null=True),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
