# Generated by Django 4.2.9 on 2024-06-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="leave", name="leave_type",),
    ]
