# Generated by Django 4.2.9 on 2024-06-05 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0001_initial"),
        ("leave", "0002_remove_leave_leave_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="department.department",
            ),
        ),
    ]
