# Generated by Django 4.2.9 on 2024-06-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0003_leave_department"),
    ]

    operations = [
        migrations.RemoveField(model_name="leave", name="department",),
    ]
