# Generated by Django 4.2.9 on 2024-06-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0005_alter_leave_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavetype",
            name="leave_days",
            field=models.IntegerField(default=30),
        ),
    ]
