# Generated by Django 4.2.9 on 2024-06-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0006_leavetype_leave_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="days",
            field=models.ImageField(default=0, upload_to=""),
        ),
    ]
