# Generated by Django 4.2.9 on 2024-06-08 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0008_alter_leave_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="leavetype",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="leave.leavetype",
            ),
        ),
    ]
