# Generated by Django 4.2.9 on 2024-06-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
        ("leave", "0010_employeeleavebalance"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="employeeleavebalance", unique_together={("employee", "leave_type")},
        ),
    ]
