# Generated by Django 4.2.9 on 2024-06-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0011_alter_employeeleavebalance_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
            ],
        ),
    ]
