# Generated by Django 4.2.9 on 2024-06-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0013_alter_holiday_date"),
    ]

    operations = [
        migrations.DeleteModel(name="Holiday",),
    ]
