# Generated by Django 4.2.9 on 2024-06-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0014_delete_holiday"),
    ]

    operations = [
        migrations.RemoveField(model_name="leave", name="isread",),
    ]
