# Generated by Django 4.2.9 on 2024-07-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0015_remove_leave_isread"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
    ]
