# Generated by Django 4.2.9 on 2024-07-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0016_leave_document"),
    ]

    operations = [
        migrations.RemoveField(model_name="leave", name="document",),
    ]
