# Generated by Django 4.2.9 on 2024-06-02 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("department", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "empcode",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=255)),
                (
                    "employee_type",
                    models.CharField(
                        choices=[
                            ("Union", "Union"),
                            ("Non-Union", "Non-Union"),
                            ("Others", "Others"),
                        ],
                        default="Non-Union",
                        max_length=10,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        default="Male",
                        max_length=10,
                    ),
                ),
                ("dob", models.DateField(auto_now_add=True)),
                ("address", models.CharField(default="80100", max_length=255)),
                ("city", models.CharField(default="Mombasa", max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("mobileno", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=10,
                    ),
                ),
                ("CreationDate", models.DateField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
