# Generated by Django 4.2.9 on 2024-06-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_employee_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
