# Generated by Django 4.2.9 on 2024-06-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=255)),
                ("department_shortname", models.CharField(max_length=50)),
                ("department_code", models.CharField(max_length=10)),
                ("CreationDate", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
